### ISSUE TITLE
[1주차 진행][아이디어 제안]

### ISSUE THREAD

**Issue by enduf7686** [PocketBand/backend-server#1]
### 추억 & 기록

- 세션 별 연습 기록 일지
    - 꾸준한 연습
    - 녹음 or 영상으로 기록
    - 그날 연습 느낌 같은 거 1~2줄 정도 같이 적으면 좋을 듯(일기 형식)

![image](https://github.com/PocketBand/backend-server/assets/37112000/e15968cb-c74e-4441-a41e-9518bd2210c9)

- 합주 일지

### 공연 같이 할 밴드 모집하기

**Comment by Elliot-KJW** [comment]
릴스, 숏폼 등의 컨텐츠 (공유 방식),
밴드방(홈페이지, 프로필) 꾸미는 기능(그래픽 요소)
